[app]
id = "tradewars"
name = "Trade Wars 2002"
description = "Clone of classic BBS door game Trade Wars 2002"
author = "Bifrost Contributors"
version = "1.0.0"
repository = "https://github.com/pmumby/bifrost"
entry_point = "main.lua"

[[assets]]
name = "tradewars_banner"
path = "assets/tradewars_banner.ans"
