[app]
id = "marketplace"
name = "Marketplace"
description = "Decentralized buy, sell, trade, and auction classifieds"
author = "Bifrost Contributors"
version = "1.0.0"
repository = "https://github.com/pmumby/bifrost"
entry_point = "main.lua"
